# Generated by Django 4.2.2 on 2023-06-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoMascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoPerro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(choices=[('Marca1', 'Marca1'), ('Marca2', 'Marca2'), ('Marca3', 'Marca3'), ('Marca4', 'Marca4')], max_length=50)),
                ('sabor', models.CharField(max_length=50)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.alimentomascota')),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoGato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(choices=[('Marca1', 'Marca1'), ('Marca2', 'Marca2'), ('Marca3', 'Marca3'), ('Marca4', 'Marca4')], max_length=50)),
                ('sabor', models.CharField(max_length=50)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.alimentomascota')),
            ],
        ),
    ]
