# Generated by Django 4.2.2 on 2023-06-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentogato',
            name='imagenURL',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentoperro',
            name='imagenURL',
            field=models.CharField(default='imagen', max_length=150),
            preserve_default=False,
        ),
    ]
