# Generated by Django 4.2.2 on 2023-06-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alimentogato_imagenurl_alimentoperro_imagenurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimentogato',
            old_name='sabor',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='alimentoperro',
            old_name='sabor',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='alimentogato',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='alimentoperro',
            name='alimento',
        ),
        migrations.AddField(
            model_name='alimentogato',
            name='cantidad',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentogato',
            name='nombre',
            field=models.CharField(default='ad', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentogato',
            name='precio',
            field=models.IntegerField(default=222222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentoperro',
            name='cantidad',
            field=models.IntegerField(default=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentoperro',
            name='nombre',
            field=models.CharField(default='da', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimentoperro',
            name='precio',
            field=models.IntegerField(default=222222223),
            preserve_default=False,
        ),
    ]
