# Generated by Django 4.2.2 on 2023-07-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_sabor_alimentogato_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InicioSesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
    ]
